### ISSUE TITLE
Require ext-intl won't work when using PHP >= 7.1

### ISSUE THREAD

**Issue by derpaschi** [wearerequired/filename-normalizer#1]
As the php-intl extension is bundled and built in since PHP 7.1 - this requirement can not be solved when using `composer install/update` with php >= 7.1

https://github.com/wearerequired/filename-normalizer/blob/master/composer.json#L28

We could increase the required php version to >= 7.1 and remove the ext-intl requirement. Other solutions welcome.

**Comment by grappler** [comment]
> We could increase the required php version to >= 7.1 and remove the ext-intl requirement.

Sounds good by me. In which project did you see this problem?

**Comment by derpaschi** [comment]
This will/should happen in every project where you use a php cli >= 7.1

**Comment by derpaschi** [comment]
(and of course just in projects where this plugin is used)

**Comment by grappler** [comment]
I don't have this problem in prohelvetia. We are running PHP 7.1 and filename-normalizer 1.0.1.

**Comment by ocean90** [comment]
To check if intl is installed use `php -m | grep intl`. It's only bundled with PHP if it was compiled with `--enable-intl`.

**Comment by derpaschi** [comment]
Just had this issue on lagoon as well when using this plugin and trying to do a `docker-compose build`. Of course i could _ignore_ this issue by adding the `--ignore-platform-reqs` switch to composer, but nah. 🤷‍♂️ 

Probably i don't get the issue right. 🤔

**Comment by ocean90** [comment]
For lagoon see "How to install more PHP extensions" on https://hub.docker.com/_/php/ or this example: https://github.com/docker-library/php/issues/57#issuecomment-418976885

https://github.com/amazeeio/lagoon/blob/master/docs/using_lagoon/docker_images/php-fpm.md

**Comment by swissspidy** [comment]
> As the php-intl extension is bundled and built in since PHP 7.1

That's the first time I have heard of this... I don't think it's true. You still have to manually install the extension.

**Comment by derpaschi** [comment]
> That's the first time I have heard of this...

Me too, but i've read it yesterday somewhere. Wasn't that good of a source, he? :D

**Comment by grappler** [comment]
@hubeRsen Were you able to find the root of the issue or did you want me to have a look?

**Comment by derpaschi** [comment]
@grappler Wasn't able so long. You could go on if you like to ;-)

**Comment by grappler** [comment]
This is not valid as `ext-intl` was missing.
